repos:
- repo: local
  hooks:
    - id: redact-it-yaml
      name: Redact it yaml
      description: This hook redacts sensitive information from yaml files.
      entry: redact-it yaml
      language: python
      types: [ text ]
      pass_filenames: false
      args: [ --config=redact-it-config.yml,  --file-path=assets/*.yml]
